baseURL: "https://durham-social-club.michael-valdron.github.io/"
languageCode: "en-us"
title: "Durham Social Club"
module:
  imports:
    - path: "gitlab.com/avron/gruvhugo"
params:
  main:
    enabled: false
    headerTitle: Durham Social Club
    quote: Welcome to the Durham Social Club!
    description:  |-
      We are a small group of people living in the Durham Region of Ontario Canada, 
      looking to help people in the area meet new friends and connect socially.
    licenseUrl: https://github.com/michael-valdron/durham-social-club/blob/main/LICENSE
  social:
    - name: facebook
      url: https://www.facebook.com/groups/durhamsocialclub
    - name: discord
      url: https://discord.gg/thHXcnw2